"""Run an admitted V2 seed through a 20-task pilot before preparing/running a batch."""

import argparse
import json
import os
from pathlib import Path

from tau3.synthesis.world_tasks import synthesize_world_tasks
from tau3.worldgen.v2.pipeline import write_json


def main():
    """Keep world qualification, pilot admission and bounded batch launch separate."""
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("world", "readiness", "config", "pilot", "output"):
        parser.add_argument(f"--{name}", type=Path, required=True)
    parser.add_argument("--local-world", type=Path)
    parser.add_argument("--num-tasks", type=int, default=200)
    parser.add_argument("--prepare-only", action="store_true")
    args = parser.parse_args()
    pilot = synthesize_world_tasks(
        args.world,
        args.readiness,
        args.pilot,
        20,
        args.config,
        600,
        resume=(args.pilot / "manifest.json").exists(),
        local_world=args.local_world,
    )
    if pilot.get("admitted_tasks") != 20:
        raise ValueError("Pilot did not admit all 20 tasks")
    command = [
        "tau3",
        "synthesize",
        "world-tasks",
        "--world",
        str(args.world),
        "--readiness",
        str(args.readiness),
        "--config",
        str(args.config),
        "--pilot-bundle",
        str(args.pilot),
        "--num-tasks",
        str(args.num_tasks),
        "--max-calls",
        str(args.num_tasks * 30),
        "--output",
        str(args.output),
    ]
    if args.local_world:
        command += ["--local-world", str(args.local_world)]
    if "TAU3_LLM_CONCURRENCY" in os.environ:
        command = [
            "env",
            "TAU3_LLM_CONCURRENCY=" + os.environ["TAU3_LLM_CONCURRENCY"],
            "TAU3_LLM_POOL=" + os.environ["TAU3_LLM_POOL"],
            *command,
        ]
    write_json(
        args.output / "launch.json",
        {
            "status": "READY",
            "command": command,
            "scope": "Admitted pilot and bounded launch; batch itself is not generated by prepare-only",
        },
    )
    if not args.prepare_only:
        result = synthesize_world_tasks(
            args.world,
            args.readiness,
            args.output,
            args.num_tasks,
            args.config,
            args.num_tasks * 30,
            resume=(args.output / "manifest.json").exists(),
            local_world=args.local_world,
            pilot_bundle=args.pilot,
        )
        print(
            json.dumps(
                {"status": result["status"], "admitted_tasks": result["admitted_tasks"]}
            )
        )
    else:
        print(
            json.dumps(
                {
                    "status": "READY",
                    "pilot_tasks": 20,
                    "batch_tasks": args.num_tasks,
                    "launch": str(args.output / "launch.json"),
                }
            )
        )


if __name__ == "__main__":
    main()
